const REVIEWS = [
  {
    id: 0,
    name: "Audrey Babcock",
    text: "Francesca is not only a dedicated vocal technician but she is patient, resourceful and hyper talented. She has boundless energy and is skilled with students of all ages regardless of background – she is encouraging, frank, and funny. As a voice professional myself, I could not recommend her higher.",
    lat: "32.79491",
    lng: "-117.07549",
    zip: "92120",
    city: 'San Diego, CA',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: "https://i.imgur.com/aPnj4vG.png",
    date: '2020-01-01',
    rating: 5,
  },
  {
    id: 1,
    name: "Sean C",
    text: "I’ve taken music lessons my whole life but my experience with Francesca has been so much more than anything else I have gotten from other teachers. She really pushes you to think outside of your comfort zone and look for your own greatness and examine the things that are holding you back. I strongly recommend her for anyone that wants to grow as an artist and musician.",
    lat: "32.79491",
    lng: "-117.07549",
    zip: "92120",
    city: 'San Diego, CA',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: "https://i.imgur.com/j873iLj.png",
    date: '2020-01-01',
    rating: 5,
  },
  {
    id: 2,
    name: "Bri G",
    text: "A perfect place from beginner to expert in music! I love my teachers Francesca and Felicia, they both have taken the time to understand my struggle as a timid shower singer and have made me feel more comfortable than ever! They challenge me in ways that keep me motivated to do what I love, while also stepping out of my comfort zone. 10/10 would recommend! Thank you to the whole Bee Hive for everything you do for us!",
    lat: "32.79491",
    lng: "-117.07549",
    zip: "92120",
    city: 'San Diego, CA',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: "https://i.imgur.com/yUz0Gmb.png",
    date: '2020-01-01',
    rating: 5,
  },
  {
    id: 3,
    name: "Giselle Chacon",
    text: "It would be impossible to convey there value of all I learned from Francesca. By the time I had worked with her for 6 months, I had gleaned so much that it will take years for me to incorporate everything she taught me, and many years more to master. Those 12 lessons would change my perspective on singing. But what she taught me on day one would change me forever- she taught me that my own misconceptions were my biggest obstacle; that I was aiming far too low in my aspirations. I went to her to find out if I was “walking” properly, and she handed me a starship! Francesca didn’t shatter my glass ceiling, she *vaporized* it! Perhaps even more importantly, she helped me overcome the greatest trigger of my gender dysphoria- the hatred of my own voice! I cannot adequately convey what she means to me in 5 stars; Francesca gave me the universe!",
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: "https://i.imgur.com/n8FepZy.png",
    city: 'San Diego, CA',
    lat: "32.79491",
    lng: "-117.07549",
    zip: "92120",
    date: '2020-01-01',
    rating: 5,
  },
  {
    id: 4,
    name: "Alecia Vultaggio",
    text: "I’ve known Francesca for many years. But to step into her buzzing studio and sit across from her as student to a master vocal professional was mind blowing. Her initial questionnaire led me to surprising insights about my presenting limitations and goals, which her in-person assessment deepened. During our session she covered anatomy, pinpointed quasi-medical issues I hadn’t thought were related, gave me stretches, massage, reading, and more, as homework. Our session felt timeless, rich, colorful, and exciting. I came away inspired to dive in, hopeful she can bring out my voice, and marked by the brilliance, presence, and passion she brings to every one of her meetings.",
    lat: "32.79491",
    lng: "-117.07549",
    zip: "92120",
    city: 'San Diego, CA',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: "https://i.imgur.com/rBOBiBk.png",
    date: '2020-01-01',
    rating: 5,
  },
  {
    id: 5,
    name: "Djamel Bettahar",
    text: "I came to BugByte Studios because I wanted to learn about music production. I started with piano lessons to get my feet wet with understanding music and have fallen in love with the instrument. Mainly because Francesca and her teachers focus on getting you playing and really enjoying music for what it is! there is technical aspects which we get into but there is this overwhelming momentum on simplifying what’s important and exciting. Which makes me want to practice and learn even more! Within days I was able to actually feel and play piano. It’s been about 2 months now and I’ve progressed way beyond what I thought I could in this short time. Before bugbyte i tried learning via youtube and its just too scattered. Its a breath of fresh air to have someone that cares about you, that creates structure and the gets you excited to learn!",
    lat: "32.79491",
    lng: "-117.07549",
    zip: "92120",
    city: 'San Diego, CA',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: "https://i.imgur.com/VO4qFUH.png",
    date: '2020-01-01',
    rating: 5,
  },
  {
    id: 6,
    name: "Andrea del Rio",
    text: "I’ve been working with Francesca for a few months now, and I feel I’ve grown so much. Prior to this I’ve sparsely attempted to play instruments, but she has taken her knowledge and passion and been able to pass that on to me while constantly reminding me that one day I will be good. And I believe it! I’ve come a long way to establish a regular practice routine, still working on it with her, and I have high expectations for the future. I recommend her to my own people and I recommend her to you.",
    lat: "32.79491",
    lng: "-117.07549",
    zip: "92120",
    city: 'San Diego, CA',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: "https://i.imgur.com/HzidZ95.png",
    date: '2020-01-01',
    rating: 5,
  },
  {
    id: 7,
    name: "Garrison Bailey",
    text: "Getting older and noticing a change in my vocal patterns was causing me some concern. Francesca not only listened to me about my concerns but she talked me through the physicality of how my vocal chords worked and how I can best sing in a way that does no damage but gets maximum range, power and tone. I have never taken vocal lessons before so this was such amazing information to have and to put into practice. When you know better, you do better. I can’t recommend BugByte Studios enough! Thanks sister!",
    lat: "32.79491",
    lng: "-117.07549",
    zip: "92120",
    city: 'San Diego, CA',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: "https://i.imgur.com/bVldCT1.png",
    date: '2020-01-01',
    rating: 5,
  },
  {
    id: 8,
    name: "Laura K Vreeland",
    text: "I have been seeing Francesca for a year now. I LOVE going to my voice lessons because I know I'm going to get so much more than just a voice lesson. She always welcomes me with an open heart and love. The studios are a nice cheerful, safe space to be vulnerable while singing. My teacher is my biggest cheerleader, that's always available for a hug or advise. I'm lucky to call her my friend now. Francesca is my voice teacher and life coach. She makes me work hard and always WANT to learn more. I really couldn't recommend her more highly. She's who you need to see if you are looking to expand your artistry. I was so glad she took my call and welcomed me into her studio. It's evident that she loves what are she does. While every pro singer in town ends up at BugByte, I also see Francesca and her assistants working with beginners. So there's room for everyone there, unsurprisingly.",
    lat: "32.79491",
    lng: "-117.07549",
    zip: "92120",
    city: 'San Diego, CA',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: "https://i.imgur.com/DZQIHg5.png",
    date: '2019-01-01',
    rating: 5,
  },
  {
    id: 9,
    name: "Anthony Amoroso",
    text: "I have been a singer-songwriter-guitarist for 17 years now, playing in bands up and down the West Coast most of that time.  I attended the LA Music Academy as a guitar player, but had never had any vocal training despite singing being my main passion as a musician.  I started taking lessons from Francesca a few months ago, and feel like I've made huge strides in my singing skills.  My live performances with my band are getting better at a rapid pace, and she's been great about teaching me techniques and new skills while helping me to keep my own personal voice.  I still have a lot to learn, and expect to be coming to Francesca at BugByte Studios for a long time.",
    lat: "32.79491",
    lng: "-117.07549",
    zip: "92120",
    city: 'San Diego, CA',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: "https://i.imgur.com/irlKNWa.png",
    date: '2020-01-01',
    rating: 5,
  },
  {
    id: 10,
    name: "Edward Spade",
    text: "Francesca is awesome! She is very knowledgeable and creates a really cool, welcoming environment. I had never had a voice instructor before and I wasn’t very confident with singing, but these sessions are really helping me work through that! Francesca is very encouraging and she creates lessons around the music that interests you! She taught me some really useful exercises to help me improve with range, pitch, etc. also, gives tools and homework to take home and practice! I’m stoked I found such a great voice instructor! Her dog is awesome too. 😎🤘",
    lat: "32.79491",
    lng: "-117.07549",
    zip: "92120",
    city: 'San Diego, CA',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: "https://i.imgur.com/S2Qlw5h.png",
    date: '2019-01-01',
    rating: 5,
  },
  {
    id: 11,
    name: "Jonathan Woods",
    text: "I have had the experience of a lifetime, learning music and singing from Francesca.  Ive always dreamed of composing and singing my own original songs, but I was intimidated at first - I didn't have a background in music and felt intimidated with how much their was to learn (and in so many different areas!).  I cannot say enough good things about Francesca and the team at BugByte Studios.  They are kind, intelligent, thoughtful, focused and incredibly passionate folks, and my experience with Francesca and her dedicated team has been truly magical, a once in a life time opportunity and I recommend that any one who has an interest in learning music, take a lesson from Francesca or her team, and you will see for yourself why BugByte is the best studio around.  The environment is safe and welcoming and I really feel the personal connection in my lessons. Francesca designed a curriculum specifically for my goals and my needs, and that makes every lesson so much fun, and she also finds creative ways to challenge me outside the classroom. Ensuring that the educational experience is enlightening and interesting , all the while being productive for my own development as an artist/singer, is just one of the many things that puts Francesca very much in a league of her own.  I am blown away, every lesson, by not only Francesca's vast knowledge and passion, but effortless dexterity in navigating the complexities of singing and music, and expressing it in a way that has not only allowed me to learn it so quickly, but allowed me to so genuinely feel immersed in the subject and all it’s beauty - I have never before met an educator who has been able to do what Francesca does, she is truly a master. I am eternally grateful for her and the opportunity to work together. It’s always been my dream to learn music and I couldn’t have imagined learning anything would be this much fun!",
    lat: "32.79491",
    lng: "-117.07549",
    zip: "92120",
    city: 'San Diego, CA',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: "https://i.imgur.com/t581fwy.png",
    date: '2020-01-01',
    rating: 5,
  },
  {
    id: 12,
    name: "Matthew Evert",
    text: "Anyone wanting to learn to harness their inner rock star needs to come see Francesca and let her work her magic.  I asked her for help a year ago and she helped me sing to the correct notes and pitches.  I can tackle a wide variety of songs and feel comfortable singing around people.  Francesca is very motivating, technical, and flexible.  Grateful to meet and work with such a passionate soul.",
    lat: "32.79491",
    lng: "-117.07549",
    zip: "92120",
    city: 'San Diego, CA',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: "https://i.imgur.com/bGWTcTl.png",
    date: '2020-01-01',
    rating: 5,
  },
  {
    id: 13,
    name: "Alethia Espinal",
    text: "Francesca has helped me on many occasions find my voice again, she is very knowledgable and crafts each lesson to her student’s needs. She has a trick or technique for nearly every challenge I encounter with plenty of support and encouragement. I have never left the studio disappointed, instead I leave ready to practice and excited for the next lesson. I would HIGHLY recommend Francesca to anyone who is interested in taking voice lessons!",
    lat: "32.79491",
    lng: "-117.07549",
    zip: "92120",
    city: 'San Diego, CA',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: "https://i.imgur.com/2wp65mv.png",
    date: '2020-01-01',
    rating: 5,
  },
  {
    id: 14,
    name: "Carolyn Brumfield",
    text: "Francesca is the real deal! Her knowledge about everything music is mind blowing but it’s her patience, love and listening that make her an amazing instructor! My daughter with Down Syndrome dreams of a music career is passionate about singing but isn’t the most coachable. Francesca is supportive and firm not only is my daughters voice improving but so is her willingness to be coached. We have also had the pleasure of working with Kinnie who brings so much light, fun and love to the studio. Thanks Bugbyte!!!",
    lat: "32.79491",
    lng: "-117.07549",
    zip: "92120",
    city: 'San Diego, CA',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: "https://i.imgur.com/BkWBx5m.png",
    date: '2020-01-01',
    rating: 5,
  },
  {
    id: 15,
    name: "Susan Simmons",
    text: "Francesca is an amazing teacher and performer. She has all the classical and pedagogical training but also sings rock. She easily and clearly explains how to get the sound and style you want. She also can guide your on-stage performance. I highly recommend her. Susan Simmons, MM Applied Voice and Voice Teacher.",
    lat: "32.79491",
    lng: "-117.07549",
    zip: "92120",
    city: 'San Diego, CA',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: "https://i.imgur.com/Hm7Zj60.png",
    date: '2020-01-01',
    rating: 5,
  },
  {
    id: 16,
    name: "Matt Slife",
    text: "Francesca Valle (Shaman of BugByte Studios)...Where do I start? Francesca is a guru. This is not sarcasm, or fluff, or any of that stuff. If you have a question about music there is a 100% chance that she will either know the answer, or know someone who does. I've known Francesca now for 8 years and have personally witnessed her ability to teach and help others. She is quite possibly the most giving person I've ever met and when you pair that with the plethora of knowledge she has about music and really just life in general, you get quite possibly the best teacher in San Diego. Whatever it is you need musically, you'd be hard pressed to find someone who can help better than she can.",
    lat: "32.79491",
    lng: "-117.07549",
    zip: "92120",
    city: 'San Diego, CA',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: "https://i.imgur.com/mjx7DGW.png",
    date: '2019-01-01',
    rating: 5,
  },
  {
    id: 17,
    name: "Giovanna Zerbi",
    text: "I love to sing but I think that I am not very good at it.  Francesca’s website caught my attention in that she claims that “singing is everybody’s birth right”.  My very first lesson made me hopeful.  Francesca is an excellent teacher, very supportive and encouraging.  She looks at the whole person, including what believes stand in the way of your innate ability to sing.  She also taught me several techniques that have already helped me improve. I love my lessons!!!",
    lat: "32.79491",
    lng: "-117.07549",
    zip: "92120",
    city: 'San Diego, CA',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: "https://i.imgur.com/655K6yG.png",
    date: '2019-01-01',
    rating: 5,
  },
  {
    id: 18,
    name: "Matt Bruno",
    text: "For the longest time I didn't like singing. I mean I wanted to but I was told quite frequently how bad my voice was and more than once (many more times) was told not to sing and just play an instrument. Kinda killed the fun.  I practiced to get better, even was the main vocalist in The Big Decisions for a bit, but I didn't really know how to practice si I didn't make a lot of progress.  So about 2 or 3 years ago I decided to take lessons to get better,  shake the negative words that stuck in my head, and make singing fun. A little way in to taking lessons elsewhere, I was introduced to Francesca Valle by a great friend and started lessons with her.  After maybe 2 years (less i think) of lessons with her, I feel a lot stronger on my voice and more confident. I've learned how to practice better and embraced my range a lot more along with a bunch of other good stuff.  If you happen to need some help with vocals, highly recommend getting in touch with Francesca. She's a pretty awesome teacher (and generally awesome person).",
    lat: "32.79491",
    lng: "-117.07549",
    zip: "92120",
    city: 'San Diego, CA',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: "https://i.imgur.com/tRS302d.png",
    date: '2020-01-01',
    rating: 5,
  },
  {
    id: 19,
    name: "Sofia",
    text: "In my first one hour consultation period with Francesca I had learned more than I did after 2 months with a previous teacher. After every class I feel that I've been doused in the holy wisdom water of music. Francesca enlightens me every time we meet and bestows the secrets of musicians upon me. Forever grateful.",
    lat: "32.79491",
    lng: "-117.07549",
    zip: "92120",
    city: 'San Diego, CA',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: "https://i.imgur.com/opywP69.png",
    date: '2020-01-01',
    rating: 5,
  },
  {
    id: 20,
    name: "Jennifer Hecht",
    text: "Francesca is amazing! I’ve been singing for most of my life and she really helped me unleash my songwriting potential (aka my biggest weakness). Anyone struggling with writers block must come see her. Oh! And if you’re a dog lover like me, she has the sweetest little pit who snuggled with me the whole session.",
    lat: "32.79491",
    lng: "-117.07549",
    zip: "92120",
    city: 'San Diego, CA',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: "https://i.imgur.com/ER2K0JL.png",
    date: '2019-01-01',
    rating: 5,
  },
  {
    id: 21,
    name: "Abby Dorsey",
    text: "A relaxed, welcoming, and warm environment to explore your voice and musical aspirations. Francesca helped me access some of the emotional blocks I was placing on my own voice. I highly recommend her to anyone who needs a comfortable, judgement-free spot to explore their creative side.",
    lat: "32.79491",
    lng: "-117.07549",
    zip: "92120",
    city: 'San Diego, CA',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: "https://i.imgur.com/nD0qQdG.png",
    date: '2019-01-01',
    rating: 5,
  },
  {
    id: 22,
    name: "George Piper",
    text: "Francesca is an incredible coach and teacher. I like how she gets into the “whys” of a certain technique instead of just telling you what to do. Makes more sense to me when I know why a certain technique works or not because of the info about the physical body and well too much to say on here I felt completely comfortable and left with knowledge! Rock on! 😎🎶🎶🎤🎤",
    lat: "32.79491",
    lng: "-117.07549",
    zip: "92120",
    city: 'San Diego, CA',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: "https://i.imgur.com/Kl1mJib.png",
    date: '2020-01-01',
    rating: 5,
  },
];
