const REVIEWS = [
  {
    id: 0,
    name: "Audrey Babcock",
    text: "Francesca is not only a dedicated vocal technician but she is patient, resourceful and hyper talented. She has boundless energy and is skilled with students of all ages regardless of background – she is encouraging, frank, and funny. As a voice professional myself, I could not recommend her higher.",
    lat: "32.79491",
    lng: "-117.07549",
    zip: "92120",
    city: 'San Diego, CA',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: "https://i.profile_picur.com/aPnj4vG.png",
    date: '2020-01-01',
    rating: 5,
  },
  {
    id: 1,
    name: "Sean C",
    text: "I’ve taken music lessons my whole life but my experience with Francesca has been so much more than anything else I have gotten from other teachers. She really pushes you to think outside of your comfort zone and look for your own greatness and examine the things that are holding you back. I strongly recommend her for anyone that wants to grow as an artist and musician.",
    lat: "32.79491",
    lng: "-117.07549",
    zip: "92120",
    city: 'San Diego, CA',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: "https://i.profile_picur.com/j873iLj.png",
    date: '2020-01-01',
    rating: 5,
  },
  {
    id: 2,
    name: "Bri G",
    text: "A perfect place from beginner to expert in music! I love my teachers Francesca and Felicia, they both have taken the time to understand my struggle as a timid shower singer and have made me feel more comfortable than ever! They challenge me in ways that keep me motivated to do what I love, while also stepping out of my comfort zone. 10/10 would recommend! Thank you to the whole Bee Hive for everything you do for us!",
    lat: "32.79491",
    lng: "-117.07549",
    zip: "92120",
    city: 'San Diego, CA',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: "https://i.profile_picur.com/yUz0Gmb.png",
    date: '2020-01-01',
    rating: 5,
  },
  {
    id: 3,
    name: "Giselle Chacon",
    text: "It would be impossible to convey there value of all I learned from Francesca. By the time I had worked with her for 6 months, I had gleaned so much that it will take years for me to incorporate everything she taught me, and many years more to master. Those 12 lessons would change my perspective on singing. But what she taught me on day one would change me forever- she taught me that my own misconceptions were my biggest obstacle; that I was aiming far too low in my aspirations. I went to her to find out if I was “walking” properly, and she handed me a starship! Francesca didn’t shatter my glass ceiling, she *vaporized* it! Perhaps even more importantly, she helped me overcome the greatest trigger of my gender dysphoria- the hatred of my own voice! I cannot adequately convey what she means to me in 5 stars; Francesca gave me the universe!",
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: "https://i.profile_picur.com/n8FepZy.png",
    city: 'San Diego, CA',
    lat: "32.79491",
    lng: "-117.07549",
    zip: "92120",
    date: '2020-01-01',
    rating: 5,
  },
  {
    id: 4,
    name: "Alecia Vultaggio",
    text: "I’ve known Francesca for many years. But to step into her buzzing studio and sit across from her as student to a master vocal professional was mind blowing. Her initial questionnaire led me to surprising insights about my presenting limitations and goals, which her in-person assessment deepened. During our session she covered anatomy, pinpointed quasi-medical issues I hadn’t thought were related, gave me stretches, massage, reading, and more, as homework. Our session felt timeless, rich, colorful, and exciting. I came away inspired to dive in, hopeful she can bring out my voice, and marked by the brilliance, presence, and passion she brings to every one of her meetings.",
    lat: "32.79491",
    lng: "-117.07549",
    zip: "92120",
    city: 'San Diego, CA',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: "https://i.profile_picur.com/rBOBiBk.png",
    date: '2020-01-01',
    rating: 5,
  },
  {
    id: 5,
    name: "Djamel Bettahar",
    text: "I came to BugByte Studios because I wanted to learn about music production. I started with piano lessons to get my feet wet with understanding music and have fallen in love with the instrument. Mainly because Francesca and her teachers focus on getting you playing and really enjoying music for what it is! there is technical aspects which we get into but there is this overwhelming momentum on simplifying what’s important and exciting. Which makes me want to practice and learn even more! Within days I was able to actually feel and play piano. It’s been about 2 months now and I’ve progressed way beyond what I thought I could in this short time. Before bugbyte i tried learning via youtube and its just too scattered. Its a breath of fresh air to have someone that cares about you, that creates structure and the gets you excited to learn!",
    lat: "32.79491",
    lng: "-117.07549",
    zip: "92120",
    city: 'San Diego, CA',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: "https://i.profile_picur.com/VO4qFUH.png",
    date: '2020-01-01',
    rating: 5,
  },
  {
    id: 6,
    name: "Andrea del Rio",
    text: "I’ve been working with Francesca for a few months now, and I feel I’ve grown so much. Prior to this I’ve sparsely attempted to play instruments, but she has taken her knowledge and passion and been able to pass that on to me while constantly reminding me that one day I will be good. And I believe it! I’ve come a long way to establish a regular practice routine, still working on it with her, and I have high expectations for the future. I recommend her to my own people and I recommend her to you.",
    lat: "32.79491",
    lng: "-117.07549",
    zip: "92120",
    city: 'San Diego, CA',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: "https://i.profile_picur.com/HzidZ95.png",
    date: '2020-01-01',
    rating: 5,
  },
  {
    id: 7,
    name: "Garrison Bailey",
    text: "Getting older and noticing a change in my vocal patterns was causing me some concern. Francesca not only listened to me about my concerns but she talked me through the physicality of how my vocal chords worked and how I can best sing in a way that does no damage but gets maximum range, power and tone. I have never taken vocal lessons before so this was such amazing information to have and to put into practice. When you know better, you do better. I can’t recommend BugByte Studios enough! Thanks sister!",
    lat: "32.79491",
    lng: "-117.07549",
    zip: "92120",
    city: 'San Diego, CA',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: "https://i.profile_picur.com/bVldCT1.png",
    date: '2020-01-01',
    rating: 5,
  },
];
