const REVIEWS = [
  {
    id: 0,
    author: "Lara Smith",
    text: "I can't say enough good things about Small World Solutions Group.  Before I found them I was on a path to bankrupcy.  After working with them, my finances are now in sound shape.  Thank you thank you!",
    lat: "33.87449",
    lng: "-118.37203",
    zip: "90278",
    city: "Redondo Beach",
  },
  {
    id: 1,
    author: "Seth Johnson",
    text: "Cathy helped me save over $250 a month on important medications.  I am so grateful to have found her.  You don't want to miss out on this opportunity!",
    lat: "33.87449",
    lng: "-118.37203",
    zip: "90278",
    city: "Redondo Beach", 
  },
  {
    id: 2,
    author: "Anna Williams",
    text: "The team at Small World Solutions are true professionals.  I recommend them to all of my friends.  They can save you thousands of dollars a year.",
    lat: "33.86479",
    lng: "-118.39719",
    zip: "90254",
    city: "Hermosa Beach", 
  },
  {
    id: 3,
    author: "Douglas Brown",
    text: "Thank you Cathy for putting me on a path to financial freedom.  I learned so much from you and your team.  This service is truly life-changing.",
    lat: "33.86479",
    lng: "-118.39719",
    zip: "90254",
    city: "Hermosa Beach", 
  },
  {
    id: 4,
    author: "Luke Jones",
    text: "Small World Solutions helped me restore my mental health after a difficult life chapter.  I am so fortunate to have found Cathy and her team.  They are the best.",
    lat: "33.88949",
    lng: "-118.4009",
    zip: "90266",
    city: "Manhattan Beach", 
  },
  {
    id: 5,
    author: "Angela Garcia",
    text: "What an incredible service.  Great people, great resources, great experience.  Small World Solutions is a true gem.",
    lat: "33.88949",
    lng: "-118.4009",
    zip: "90266",
    city: "Manhattan Beach", 
  },
];
