// reviews data
const REVIEWS = [
{
    id: 0,
    name: 'John Doe',
    rating: 5,
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quidem. lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quidem.',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: 'https://i.pravatar.cc/',
    date: '2020-01-01',
    city: 'New York',
    lat: 40.730610,
    lng: -73.935242,
},
{
    id: 1,
    name: 'John Doe',
    rating: 5,
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quidem.',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: 'https://i.pravatar.cc/',
    date: '2020-01-01',
    city: 'Delhi',
    lat: 28.7041,
    lng: 77.1025,
},
{
    id: 2,
    name: 'John Doe',
    rating: 5,
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quidem.',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: 'https://i.pravatar.cc/',
    date: '2020-01-01',
    city: 'Mumbai',
    lat: 19.0760,
    lng: 72.8777,
},
{
    id: 3,
    name: 'John Doe',
    rating: 5,
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quidem.',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: 'https://i.pravatar.cc/',
    date: '2020-01-01',
    city: 'Dubai',
    lat: 25.2048,
    lng: 55.2708,
},
{
    id: 4,
    name: 'John Doe',
    rating: 5,
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quidem.',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: 'https://i.pravatar.cc/',
    date: '2020-01-01',
    city: 'London',
    lat: 51.5,
    lng: -0.1,
},
{
    id: 5,
    name: 'John Doe',
    rating: 5,
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quidem.',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: 'https://i.pravatar.cc/',
    date: '2020-01-01',
    city: 'Paris',
    lat: 48.8566,
    lng: 2.3522,
},
{
    id: 6,
    name: 'John Doe',
    rating: 5,
    text: 'Lorem ipsum dolor sit amet',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: 'https://i.pravatar.cc/',
    date: '2020-01-01',
    city: 'Quebec',
    lat: 46.8138,
    lng: -71.2080,
},
{
    id: 7,
    name: 'John Doe',
    rating: 5,
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quidem.',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: 'https://i.pravatar.cc/',
    date: '2020-01-01',
    city: 'Amsterdam',
    lat: 52.3738,
    lng: 4.8910,
},
{
    id: 8,
    name: 'John Doe',
    rating: 5,
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quidem.',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: 'https://i.pravatar.cc/',
    date: '2020-01-01',
    city: 'Sydney',
    lat: -33.8688,
    lng: 151.2093,
},
{
    id: 9,
    name: 'John Doe',
    rating: 5,
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quidem.',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: 'https://i.pravatar.cc/',
    date: '2020-01-01',
    city: 'Tokyo',
    lat: 35.6762,
    lng: 139.6503,
},
{
    id: 10,
    name: 'John Doe',
    rating: 5,
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quidem.',
    logo: 'https://1000logos.net/wp-content/uploads/2016/11/New-Google-Logo.jpg',
    profile_pic: 'https://i.pravatar.cc/',
    date: '2020-01-01',
    city: 'New York',
    lat: 40.7128,
    lng: -74.0060,
}
]