const REVIEWS = [
  {
    id: 0,
    zip: "90601",
    lat: "34.00327",
    lng: "-118.02612",
    city: "City of Industry, CA",
    author: "Joy Displays",
    text: "Neat office with warehouse space. Staffs maintain this facility to be as clean and comfortable as possible.",
  },     
  {
    id: 1,
    zip: "90601",
    lat: "34.00327",
    lng: "-118.02612",
    city: "City of Industry, CA",
    author: "Malcolm Fung",
    text: "The place was nice and clean. Management was nice and always available.",
  },
  {
    id: 2,
    zip: "90601",
    lat: "34.00327",
    lng: "-118.02612",
    city: "City of Industry, CA",
    author: "Apple EventSupplies",
    text: "This place is conveniently right off the freeway it is always clean and presentable for your customers. The Staff is very friendly and attentive.",
  },
  {
    id: 3,
    zip: "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "MW Lighting",
    text: "We have been here for some years. We are using the office and warehouse facility. Great location, very convenient, not too far from the free way. Good security system, office and other area is very clean and tidy. Management staff are all friendly and nice.",
  },
  {
    id: 4,
    zip: "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "Michael Lee",
    text: "I fell in love with this place first time I visited after seeing my friend sign up with these guys. I've toured a couple of their locations and decided to sign up for the Ontario one. Their salespeople are some of the friendliest that I've ever met! Everyone else in the building is also super nice as well. Will be getting to know as many of them as I can so I can start networking my business.",
  },
  {
    id: 5,
    zip: "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "Robert Chang",
    text: "Wooot! Just signed up for my space today! Their setup is unlike anything I've ever seen before. They made it super easy for me to sign up and I'm glad I did! I'm excited to start moving in! Time to start getting down to business!",
  },
  {
    id: 6,
    zip: "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "Catherine Chen",
    text: "Thanks to Elizabeth, Brian and Auggie for making my move into your warehouse quick and easy. The staffs are all very helpful, the facility is always clean and organized. Cubework provides unlimited expansion possibilities to all tenants. Great place to land your business.",
  },
  {
    id: 7,
    zip: "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "Johnny Ma",
    text: "Overall, we at DMA Transportation are very pleased with the rental experience. Eunice and Angela, the City of Industry representatives, have been fantastic to work with. They treat tenants well and handle facility requests in a professional demeanor. Our facility has experienced upgrades in several levels-- starting with lights, recycle bins, and now wooden floors are being installed in the office to replace the used carpet.",
  },
  {
    id: 8,
    zip: "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "Lay Chray",
    text: "Great shared warehousing solution. Regardless of your business size this will work for you and the best part is the fact that the workers at cubework perform their top diligence to ensure you have what is necessary to have your business thrive and grow. I would highly recommend using them.",
  },
  {
    id: 9,
    zip: "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "Justin Alfrey",
    text: "Fantastic place to rent some space!  The price you pay is a little more per square foot but when you factor in the included utilities, cleaning services, package and mail handling, co-working space, shared loading docks and ramps, and more, the rent is more than worth it.  Fantastic for businesses small and large, from 300 sq. ft. to 100,000+!",
  },
  {
    id: 10,
    zip:  "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "Cami Wang",
    text: "Thanks for making my move into your warehouse quick and easy last year. Your sales rep helped my furniture Ecom business grow from your City of Industry location to our second distribution space in Atlanta this past month. Definitely recommend Cubework for storage and warehouse space. 👍🏻",
  },
  {
    id: 11,
    zip:  "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "Mark Hendry",
    text: "Cubework has been amazing for our business The Heart Supply. Cubework has allowed us to execute in our studio space as well as utilize the warehouse to ship products under the same roof. Our management is very helpful and keeps the building very clean, as well as helps with all of our business needs. 5 stars for Cubework!",
  },
  {
    id: 12,
    zip:  "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "Eva Hsieh",
    text: "Great shared warehouse and office spaces.  Common areas, such as the lunch room and bathroom, are always clean and equipped with essentials items.  Staffs are always courteous and quick to respond to any questions I have.  Keep it up and highly recommended.",
  },
  {
    id: 13,
    zip:  "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "Doug H",
    text: ". I have to say this company is awesome. We moved in one of their facilities back to 2 years ago and we are satisfied everything they've done for us. The manager is nice and kind, the management team is super cooperative. They are really helpful and this helps our business going smoothly. If you ever think about getting a facility, check it out with Cubework. You will be happy.",
  },
  {
    id: 14,
    zip:  "90670",
    lat: "33.92325",
    lng: "-118.05757",
    city: "Santa Fe Springs, CA",
    author: "Jason M.",
    text: "I've been at the cubework location at Santa Fe Springs for about 3 months now. I just do E-commerce there on the side since I have another main retail location which is packed. The employees over there are cooler than frozen yogurt and I always chat with them on a regular basis when I'm there. Anna has always helped me receive my packages from USPS and is super sweet.",
  },
  {
    id: 15,
    zip:  "30093",
    lat: "33.90595",
    lng: "-84.18073",
    city: "Norcross, GA",
    author: "Rena's Recipe Team",
    text: "We began renting a space in Norcross, Georgia location since the beginning of this year and we absolutely LOVE it!  Great location close to I-85 and 24 hours access  it definitely makes our job much easier!  The staff are all nice and friendly too!",
  },
  {
    id: 16,
    zip:  "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "Jamie Garelli",
    text: "We've been with Cubework for a few month now and really love the operations. It gives small businesses the opportunity to test out their ideas without long term commitments to a warehouse. We're exited to expand with Cubework and look forward to joining other facilities across CA.",
  },
  {
    id: 17,
    zip:  "30093",
    lat: "33.90595",
    lng: "-84.18073",
    city: "Norcross, GA",
    author: "J Park",
    text: "Very friendly and personable staff! We love renting space at the Norcross GA location! The entire warehouse is very well maintained! The rent with all utilities included is very affordable! Love it!",
  },
  {
    id: 18,
    zip:  "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "David Yang",
    text: "These guys are legit, and got me the space I needed to start and grow my business. I currently have 5000 sq ft of space with them and will need to expand soon. Luckily they are good at helping me expand each time! First it was 2000 sq ft, then it was 5000 sq ft, now I need 8000 sq ft!",
  },
  {
    id: 19,
    zip:  "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "Juan Carlos",
    text: "Love working at Cubework! Their service and staff are awesome! I love their Wellness Appreciation Day where they give everyone fresh fruits. Shows they appreciate me even 5 months after I signed with them!",
  },
  {
    id: 20,
    zip:  "92614",
    lat: "33.68411",
    lng: "-117.82754",
    city: "Irvine, CA",
    author: "Carin McKay",
    text: "Irvine has a great co-working environment.  Friendly staff who is always helpful, the office is designed nicely and common spaces are always clean and organized.  When coming down to work at the Irvine Office with Tax Relief Network, LLC, it is always a pleasant experience.  Just wish they has a CubeWork in San Luis Obispo.",
  },
  {
    id: 21,
    zip:  "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "Tanner's",
    text: "Coffee Got some warehouse space near long beach port on a 3 month agreement. Very flexible and easy process. Friendly staff and professional. Dont know of any other place renting exact spaces on short term leases",
  },
  {
    id: 22,
    zip:  "90501",
    lat: "33.83024",
    lng: "-118.31354",
    city: "Torrance, CA",
    author: "Joo Cho",
    text: "Im renting small office in torrance. Its been 2 months. Its been great no stress.  They literally provide everything for free and i get access to conference room. There was not any surprise or hidden fees. Will be extending when my current agreement is up.",
  },
  {
    id: 23,
    zip:  "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "Richard Huang",
    text: "Cubework is truly a great solution for companies that need additional warehouse space. We have been using CubeWork for more than a year. The facility is clean, safe, very well managed. KEEP IT UP.",
  },
  {
    id: 24,
    zip:  "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "Ezra Roches",
    text: "My place of work and I love it. It's safe and it's sanitary. We have fruit trees for shade and a Keurig; couldn't ask for more.",
  },
  {
    id: 25,
    zip:  "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "Bill W",
    text: ". This place is great for small business or startup who looking for both office space and inventory space with limited budget. I am an Amazon seller and running my own Shopify store. This is perfect match what we need.",
  },
  {
    id: 26,
    zip:  "90501",
    lat: "33.83024",
    lng: "-118.31354",
    city: "Torrance, CA",
    author: "Dong Lee",
    text: "Im renting office and warehouse in cubework torrance . Took a bit to get internet and my partitions done but now that everything is up and running i m super happy. Dont have to pay for any utilities and they even provide free coffee! Will be staying here for a long time!",
  },
  {
    id: 27,
    zip:  "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "Tiffany Wang",
    text: "Great shared warehouse and office spaces.  all utilities included is very affordable!  all the staff are friendly！would highly recommend using them.",
  },
  {
    id: 28,
    zip:  "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "Lidia Lee",
    text: "Cubework is helping me get some storage space since I am moving. I don’t have to sign long contract and they let me have 24/7 access. So nice.",
  },
  {
    id: 29,
    zip:  "92614",
    lat: "33.68411",
    lng: "-117.82754",
    city: "Irvine, CA",
    author: "Jessica Xu",
    text: "I rent Cubework Irvine as my office and it's a nice place to stay and work. Workers are nice and the environment is pretty good. I enjoyed the working time here",
  },
  {
    id: 30,
    zip:  "92614",
    lat: "33.68411",
    lng: "-117.82754",
    city: "Irvine, CA",
    author: "Jason Wang",
    text: "I love Cubework. I have a space in the Irvine location. People and staff are friendly. Facility is safe, clean, and spacious. Thank you Cubework!",
  },
  {
    id: 31,
    zip:  "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "Luis Ramirez",
    text: "I'm very excited to expand my business in California, the support and great customer service from Cubework staff has been key to achieving this goal. Thank you very much Cubework!",
  },
  {
    id: 32,
    zip:  "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "Jackie-Boy Rodriguez",
    text: "3 month leases, any square footage, full service included in price, simply the best for startups or large companies",
  },
  {
    id: 33,
    zip:  "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "Anthony Coombs",
    text: "Great space and good staff of people to work with. Terrific concept which is perfect for a growing business. Would recommend.",
  },
  {
    id: 34,
    zip:  "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "Francisco Suarez",
    text: "It is an excellent place to start your business, I have a space in this warehouse !!  I highly recommend it",
  },
  {
    id: 35,
    zip:  "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "Carlos Cedano",
    text: "Great place. Great people. ",
  },
  {
    id: 36,
    zip:  "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "Xiangxin Lee",
    text: "Good space ,very kind staff, fast internet,that's convenience to our company. I will recommend to my friend.",
  },
  {
    id: 37,
    zip:  "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "Bestcars Auto Sale",
    text: "Cubework is a perfect space with friendly staff! Very clean and organized community.Thank you CUBEWORK!!!",
  },
  {
    id: 38,
    zip:  "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "Launch Protect",
    text: "Cubework is a great place! Staff is friendly and attentive. Highly Recommend!",
  },
  {
    id: 39,
    zip:  "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "Wendy Wawrzyniak",
    text: "Great Flexible Storage Solutions Supporting Our Mobile Technician Teams",
  },
  {
    id: 40,
    zip:  "90501",
    lat: "33.83024",
    lng: "-118.31354",
    city: "Torrance, CA",
    author: "Lori B",
    text: "Great place to work with! Love my space!! At the Torrance location!",
  },
  {
    id: 41,
    zip:  "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "William Liang",
    text: "Great place to rent if you’re an SMB",
  },
  {
    id: 42,
    zip:  "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "Michael Bina",
    text: "This is a great work place.  Clean, orderly with responsive management.",
  },
  {
    id: 43,
    zip:  "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "Emilia Gonzalez",
    text: "Great space to rent for small business!",
  },
  {
    id: 44,
    zip:  "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "How To Enjoy Stuff",
    text: "You should come here for your warehouse.",
  },
  {
    id: 45,
    zip:  "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "Martin Lopez",
    text: "It's a good place to start a business",
  },
  {
    id: 46,
    zip:  "91745",
    lat: "34.00181",
    lng: "-117.98336",
    city: "City of Industry, CA",
    author: "Jonathan Huang",
    text: "I like the scalable flexibility.",
  },
  {
    id: 47,
    zip:  "94544",
    lat: "37.63681",
    lng: "-122.04943",
    city: "Hayward, CA",
    author: "PC Gan",
    text: "They are the best third party partner I have ever met. Cubework team really cares customers. Tavio always try to improve the whole team's service level and always reply my message so quickly. Miguel always helps us at the most critical time. One of our trucker came late to pick up our container , Miguel answered my phone at 10:00pm and helped us to open the gate for our trucker.  Maria is the most reliable friend, When every time our trucker arrives, she always let me know immediately.  Cubework team really make my work much easier, I am really enjoy the time to work with them.",
  },
  {
    id: 48,
    zip:  "92614",
    lat: "33.68411",
    lng: "-117.82754",
    city: "Irvine, CA",
    author: "Launch Protect",
    text: "Cubework provides great tenant customer service! They really accommodate to any size business.",
  },
  {
    id: 49,
    zip:  "92614",
    lat: "33.68411",
    lng: "-117.82754",
    city: "Irvine, CA",
    author: "Bestcars Auto Sale",
    text: "Very organized and clean community. Friendly staff and excellent customer service!!",
  },
  {
    id: 50,
    zip:  "92614",
    lat: "33.68411",
    lng: "-117.82754",
    city: "Irvine, CA",
    author: "Michael Casner",
    text: "Very friendly staff and highly recommend using them!",
  },
  {
    id: 51,
    zip:  "92337",
    lat: "34.05186",
    lng: "-117.46688",
    city: "Fontana, CA",
    author: "Fernando Robles",
    text: "Great place",
  },
  {
    id: 52,
    zip:  "93706",
    lat: "36.64125",
    lng: "-119.90476",
    city: "Fresno, CA",
    author: "Celeste Michler",
    text: "A warehouse that stores large truck deliveries. I know the manager,  he is always there and great to work with!!",
  },
  {
    id: 53,
    zip:  "90638",
    lat: "33.90083",
    lng: "-118.00718",
    city: "La Mirada, CA", 
    author: "George Chiao",
    text: "My first location with CW is their La Mirada location. Everyone from their sales to customer service staff have been extremely helpful. We’re glad we went with Cubework instead of the other competitors nearby. I now have expanded my business into Texas and we’re so happy we were able to work with our CA sales rep to help secure a space out in Dallas and Houston.",
  },
  {
    id: 54,
    zip:  "90638",
    lat: "33.90083",
    lng: "-118.00718",
    city: "La Mirada, CA", 
    author: "Kunal Krishan",
    text: "Awesome place to get loaded. There is no space to maneuver, but once you park it takes them 20 minutes to load.",
  },
  {
    id: 55,
    zip:  "91761",
    lat: "34.0267",
    lng: "-117.58745",
    city: "Ontario, CA",
    author: "Beverly Perez",
    text: "Awesome people and service",
  },
  {
    id: 56,
    zip:  "91761",
    lat: "34.0267",
    lng: "-117.58745",
    city: "Ontario, CA",
    author: "Jackie-Boy Rodriguez",
    text: "Great Services",
  },
  {
    id: 57,
    zip:  "90221",
    lat: "33.88007",
    lng: "-118.20128",
    city: "Compton, CA",
    author: "Vladimir Ilyin",
    text: "Excellent warehouse. I have been renting a warehouse for 1 year. What I like the most is flexibility. Now I need a warehouse of 1000 sq. Ft. Tomorrow 5000 sq. Ft. All of these options can be found in Cubework.",
  },
  {
    id: 58,
    zip:  "92508",
    lat: "33.88878",
    lng: "-117.32142",
    city: "Riverside, CA",
    author: "Secondchance Music Chance",
    text:  "The company I work for rents space here. They are helpful and it's a secured place to park your trucks.",
  },
  {
    id: 59,
    zip:  "90670",
    lat: "33.92325",
    lng: "-118.05757",
    city: "Santa Fe Springs, CA",
    text: "Dylan Cohen Great place for storage ans warehousing of all sizes, clean property and easy going staff!",
  },
  {
    id: 60,
    zip:  "90501",
    lat: "33.83024",
    lng: "-118.31354",
    city: "Torrance, CA",
    author: "RC Integrated Systems LLC",
    text: "We have rented an office from Cubework in Torrance a year ago. It's a very nice place. It's neat and clean. You can always expand your workspace by renting additional offices or warehouse space when needed.",
  },
  {
    id: 61,
    zip:  "90501",
    lat: "33.83024",
    lng: "-118.31354",
    city: "Torrance, CA",
    author: "Lori Brummel",
    text: "Love this office space! I have been in the building for nearly a year. It’s a quiet building, great space and convenient parking. Would definitely recommend it!",
  },
  {
    id: 62,
    zip:  "90501",
    lat: "33.83024",
    lng: "-118.31354",
    city: "Torrance, CA",
    author: "John Koski",
    text: "Great place for business. Clean and calm. The company is helpful and supportive. Highly recommended.",
  },
  {
    id: 63,
    zip:  "30093",
    lat: "33.90595",
    lng: "-84.18073",
    city: "Norcross, GA",
    author: "Nami N.",
    text: "I began renting a storage space here since last year. I feel very safe to work in there and the staff there is very nice and they are working hard to make the place better! I'm really glad I found this place!",
  },
  {
    id: 64,
    zip:  "30093",
    lat: "33.90595",
    lng: "-84.18073",
    city: "Norcross, GA",
    author: "JJ Liew",
    text: "They provide fully service and good environment. It is safe and professional management. Good choice for small business startup!",
  },
  {
    id: 65,
    zip:  "60712",
    lat: "42.00618",
    lng: "-87.73623",
    city: "Lincolnwood, IL",
    author: "Matthew Conte",
    text: "Leased a large amount of space here for a period of 2 years. Was the perfect solution for my rapidly growing business. Have since outgrown the space and moved into my own built-out building, but the flexibility of Cubework was essential in helping my business stay lean and achieve the growth that we saw.  Alen was/is a great building manager, and accommodating especially with the move-out process as it was fraught with delays out of our control. Always happy to recommend Cubework to fellow entrepreneurs who need that flexible space but can't justify a 3-year commitment that comes with a traditional lease.",
  },
  {
    id: 66,
    zip:  "60712",
    lat: "42.00618",
    lng: "-87.73623",
    city: "Lincolnwood, IL",
    author: "Ben Bridger",
    text: "An excellent place to lease space for small businesses, really any size business because they can customize space for anyone. The community manager is very helpful and they keep very clean facilities.",
  },
  {
    id: 67,
    zip:  "60712",
    lat: "42.00618",
    lng: "-87.73623",
    city: "Lincolnwood, IL",
    author: "Muamer Besic",
    text: "Professional staff, clean warehouse, nice loading docks. Our trucking company delivers a few times a month to this location.",
  },
  {
    id: 68,
    zip:  "60712",
    lat: "42.00618",
    lng: "-87.73623",
    city: "Lincolnwood, IL",
    author: "Josh Ebert",
    text: "I rented space from Cubework and was very happy with the accommodations and service. Alan is very responsive and a pleasure to work with! Highly recommended!",
  },
  {
    id: 69,
    zip:  "60712",
    lat: "42.00618",
    lng: "-87.73623",
    city: "Lincolnwood, IL",
    author: "Bindu Thomas",
    text: "The company I am working for ( Kidorable)  moved to Cubework (Lincolnwood,IL location) a few months ago and we have an office and warehouse space. The staff has been accommodating and friendly and made some great welcoming changes to both and guests and tenants. Would highly recommend",
  },
  {
    id: 70,
    zip:  "60712",
    lat: "42.00618",
    lng: "-87.73623",
    city: "Lincolnwood, IL",
    author: "Angel Minaro",
    text: "I have a space at their location in Lincolnwood, it is a great space, with very helpful staff too. I highly recommend them!",
  },
  {
    id: 71,
    zip:  "60712",
    lat: "42.00618",
    lng: "-87.73623",
    city: "Lincolnwood, IL",
    author: "Smajo Jay",
    text: "Clean warehouse and very professional management.",
  },
  {
    id: 72,
    zip:  "60712",
    lat: "42.00618",
    lng: "-87.73623",
    city: "Lincolnwood, IL",
    author: "Urmat Sovetov",
    text: "Professionals, easy to work with, convenient process!",
  },
  {
    id: 73,
    zip:  "60712",
    lat: "42.00618",
    lng: "-87.73623",
    city: "Lincolnwood, IL",
    author: "Darrell Washington",
    text: "Great place nice atmosphere.",
  },
  {
    id: 74,
    zip:  "60712",
    lat: "42.00618",
    lng: "-87.73623",
    city: "Lincolnwood, IL",
    author: "Maor Dav",
    text: "Great for professionals",
  },
  {
    id: 75,
    zip:  "97220",
    lat: "45.55191",
    lng: "-122.55533",
    city: "Portland, OR",
    author: "Daniel Madrid",
    text: "Very helpful staff and they have all the space I needed to run my business. Big or small, short term or long",
  },
  {
    id: 76,
    zip:  "38118",
    lat: "35.03883",
    lng: "-89.92757",
    city: "Memphis, TN",
    author: "The Platinum Pearl",
    text: "Cubework has met every expectation I have had as a tenant in their warehouse ! They work fast to fix any issues you may have and my products are secured and I love the atmosphere. I would recommend anyone to do business with this company !!",
  },
  {
    id: 77,
    zip:  "38118",
    lat: "35.03883",
    lng: "-89.92757",
    city: "Memphis, TN",
    author: "Etanda Dembo",
    text: "Great job",
  },
  {
    id: 78,
    zip:  "75019",
    lat: "32.9601",
    lng: "-96.98266",
    city: "Coppell, TX",
    author: "Cargo Mark",
    text: "We recently moved into Cubework and really excited about our newly leased space. We worked with Sara to get our deal done and she has surpassed our expectations. Her attention to detail and customer service level is top notch. We look further to expand our working relationship with Cubework",
  },
  {
    id: 79,
    zip:  "75019",
    lat: "32.9601",
    lng: "-96.98266",
    city: "Coppell, TX",
    author: "George Chiao",
    text: "We’re happy we found cubework as an alternative to signing a long term lease and using a larger space than necessary. I currently have 3 locations  with them throughout their different districts. They offered me flexibility in terms and they gave me the ability to customize the size of my units!!! definitely helped my business expand into new markets. I’m now looking into their east coast locations for the end of the year!",
  },
  {
    id: 80,
    zip:  "77003",
    lat: "29.74883",
    lng: "-95.34384",
    city: "Houston, TX",
    author: "George Chiao",
    text: "We’re happy with our new space out here in DT Houston. The Sales and Customer Service were extremely helpful and helped us move into our space within a week.",
  },
];


