const REVIEWS = [
  {
    id: 0,
    author: "Luisa M",
    text: "Figgi matched me with a doula that I had an instant connection with. She understood me and listened without judgement. My doula supported me through the tough times when I felt like a failure. She was my guiding light.",
    lat: "33.87449",
    lng: "-118.37203",
    zip: "90278",
    city: "My Guiding Light",
  },
  {
    id: 1,
    author: "Hannah H.",
    text: "My experience with my postpartum doula Ashleigh has been great! She's really knowledgeable and supportive. It's nice to have her expertise outside of all the other people giving advice in the parenting realm. She is truly a gem and I'm so grateful to have her.",
    lat: "33.87449",
    lng: "-118.37203",
    zip: "90278",
    city: "My experience has been great!",
  },
  {
    id: 2,
    author: "Helene S.",
    text: "My expert Hali was beyond resourceful, not only in answering my questions but providing great insights and guidance for each week of my baby's development. It was great having a professional answer the questions you may have otherwise asked a a friend. As a second-time mom, I was surprised that I had much different questions and needed new answers. Baby #2 had issues with taking bottles, which I hadn't experienced before. Hali helped me find new ways to introduce bottles to her. She also sent me schedules to stick to which was helpful in getting her into a routine.",
    lat: "33.87449",
    lng: "-118.37203",
    zip: "90278",
    city: "The professional resource you need",
  },
  {
    id: 3,
    author: "Leslie C.",
    text: "I went from a terrified first time mom fresh out of a month long NICU stay to feeling like I wasn’t totally on my own thanks to Hali. After just one month of working with New Kind, I felt like I had a solid knowledge resource and I didn't have to do endless research for one question. I could just go to one place and feel confident in the answer. You can’t place a price on peace of mind, especially for a FTM.",
    lat: "33.87449",
    lng: "-118.37203",
    zip: "90278",
    city: "Terrified to Confident FTM",
  },
  {
    id: 4,
    author: "Cara W.",
    text: "As a first-time mom, it has been so amazing to have access to my doula whenever I need it. I can text, email, or FaceTime her to ask any question I might have. When I was expecting I was able to take childbirth classes, lactation class, and newborn care class for me and my partner that helped me feel super prepared for our little ones arrival.",
    lat: "33.87449",
    lng: "-118.37203",
    zip: "90278",
    city: "A must have for all first-time moms",
  },
  {
    id: 5,
    author: "Deirdre W.",
    text: "Motherhood is hard and it takes a village. You need a guru to help with all the things that pop up. Hali cheers me on and helps guide me through each step. I don't produce enough milk to breastfeed exclusively, but she helps me maximize what I can produce. She came up with a pumping schedule that is realistic and keeps me on track through her proactive check-ins.",
    lat: "33.87449",
    lng: "-118.37203",
    zip: "90278",
    city: "Your own newborn + breastfeeding guru",
  },
  {
    id: 6,
    author: "Alejandra L.",
    text: "It was amazing having someone proactively check-in on me. I felt reassured and heard. Hali was very thorough when offering advice and made me feel confident. She was willing to work on coming up with a plan for each of my needs. In particular, all of the sleep advice I got from her was invaluable.",
    lat: "33.87449",
    lng: "-118.37203",
    zip: "90278",
    city: "Felt more confident and reassured",
  },
  {
    id: 7,
    author: "Angela F.",
    text: "Postpartum care puts a lot of focus primarily on baby, but my doula looked out for the well-being of both my newborn and myself as a first-time mom - I so appreciated her informational and encouraging support, which helped give me the confidence I needed to believe that I am capable of this.",
    lat: "33.87449",
    lng: "-118.37203",
    zip: "90278",
    city: "I am capable of this",
  },
];
