const REVIEWS = [
  {
    id: 0,
    author: "Mel",
    lat: "39.33348",
    lng: "-76.78445",
    zip: "21244",
    city: "Windsor Mill, MD",
    text: "Oh. My. Gosh. That was sooooooo good, Kristen! I ate it all without even taking a picture!",
  },
  {
    id: 1,
    author: "Kia",
    lat: "39.33348",
    lng: "-76.78445",
    zip: "21244",
    city: "Windsor Mill, MD",
    text: "Everything was delicious! I will definitely be ordering again…You are my new best friend!",
  },
  {
    id: 2,
    author: "Keisha",
    lat: "39.33348",
    lng: "-76.78445",
    zip: "21244",
    city: "Windsor Mill, MD",
    text: "Oh my goodness! No way that food was Keto!!!!",
  },
  {
    id: 3,
    author: "Finibus",
    lat: "39.33348",
    lng: "-76.78445",
    zip: "21244",
    city: "Windsor Mill, MD",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
  },
  {
    id: 4,
    author: "Bonorum",
    lat: "39.33348",
    lng: "-76.78445",
    zip: "21244",
    city: "Windsor Mill, MD",
    text: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
  },
  {
    id: 5,
    author: "Malorum",
    lat: "39.33348",
    lng: "-76.78445",
    zip: "21244",
    city: "Windsor Mill, MD",
    text: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ",
  },
];
